### ISSUE TITLE
I have a problem "No such file or directory: 'Matrices\\1Kb_gene.mtx'"

### ISSUE THREAD

**Issue by davidyx95** [asroopra/MAGIC#2]
hello,
I unzipe the Matices in the same flod which include the MAGIC.py, but when show the below words:
''
- Enter the number corresponding to the matrix to be used:
[1]...1Kb_gene
[2]...1Kb_gene_with_engineered_factors
[3]...1Kb_promoter
[4]...1Kb_promoter_with_engineered_factors
[5]...5Kb_gene
[6]...5Kb_gene_with_engineered_factors
''
I iuput " 1 ",
But I have the following error:
"
- Extracting Matrix Data.
Traceback (most recent call last):
  File "MAGIC.py", line 914, in <module>
    TFs, mtxGenes  = magicExtractor(magicPath)
  File "MAGIC.py", line 175, in magicExtractor
    data   = open(path).read().splitlines()
FileNotFoundError: [Errno 2] No such file or directory: 'Matrices\\1Kb_gene.mtx'
" 
Can you tell why I have this problem?
Thank you very much!!

**Comment by wigge206** [comment]
I am having the identical problem, due you resolve this?

**Comment by MSajek** [comment]
Hi all,
I had the same problem. It looks like script recognizes linux as windows. The solution is really simple, you have to make changes in two lines:
line 35 should be changed from:
`separator = "\\"`
to:
`separator = "/"`
identical change should be done in line 114
